# Generated by Django 5.2 on 2025-08-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
