# Generated by Django 5.2 on 2025-08-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_course_image_field_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
    ]
