# Generated by Django 5.2 on 2025-08-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_course_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='image',
        ),
    ]
