services:
  - type: web
    name: academix
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn AcademiX.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString